name: Deploy To S3 And Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm i

      - name: 빌드하기
        run: npm run build

      - name: AWS Resource 액세스 설정1
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일 전체 삭제
        run: aws s3 rm --recursive s3://oz-aws-test-3

      - name: S3 빌드 파일 업로드
        run: aws s3 cp ./dist s3://oz-aws-test-3/ --recursive

      - name: CloudFront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id ECIJAN3LT8VXE --paths "/*"
